Mhid: []
Nhid:
- 64
- 128
- 128
alpha: 0.7
alpharp:
- 0.65
batch_size: 60
beta:
- 0.92
betas:
- 0.0
- 0.95
burnin_steps: 1
chunk_size_test: 20
chunk_size_train: 20
dataset: torchneuromorphic.motoneurons.mn_dataloaders
deltat: 1000
init_theta:
- 5.0e-05
- 5.0e-05
- 5.0e-05
- 5.0e-05
input_shape: []
kernel_size:
- 3
lc_ampl: 0.5
learning_method: rtrl
learning_rate: 1.0e-06
loss: smoothL1
lr_drop_factor: 5
lr_drop_interval: 30
muscle_to_exclude: []
num_conv_layers: 3
num_dl_workers: 4
num_epochs: 100
num_layers: 3
num_mlp_layers: 0
online_update: true
optimizer: adamax
out_channels: 9
overlap_size_test_perc: 0
overlap_size_train_perc: 0
pool_size:
- 2
- 1
- 2
random_tau: true
reg_l:
- 0.0
- 0.0
- 0.0
- 0.0
test_interval: 1
