Nhid:
- 64
- 128
- 128
Mhid: []
alpha:
- 0.75
alpharp:
- 0.65
batch_size: 60
beta:
- 0.97
betas:
- 0.0
- 0.95
burnin_steps: 60
chunk_size_test: 200
overlap_size_test_perc: 0.9
chunk_size_train: 200
overlap_size_train_perc: 0.9
dataset: mn_dataloaders2
perc_test_norm: 0.1
filename: data/motoneurons/MNDS_KaJu_5ClassesFlxFing_AllPost_IP.mat
deltat: 1000
input_shape: []
kernel_size:
- 3
lc_ampl: 0.5
learning_rate: 1.e-6
loss: smoothL1
lr_drop_factor: 2
lr_drop_interval: 30
num_layers: 3
num_epochs: 100
num_conv_layers: 3
num_mlp_layers: 0
num_dl_workers: 4
optimizer: adamax
out_channels: 10
pool_size:
- 2
- 1
- 2
random_tau: False
reg_l:
- .0
- .0
- .0
- .0
test_interval: 1
init_theta:
- 5.e-5
- 5.e-5
- 5.e-5
- 5.e-5
muscle_to_exclude: []
class_to_include: []
thr_firing_excl_slice: 0
online_update: True
learning_method: 'rtrl'
