Nhid:
- 64
- 128
Mhid: []
alpha: 0.97
alpharp:
- 0.65
batch_size: 30
beta: 0.75
betas:
- 0.0
- 0.95
burnin_steps: 60
chunk_size_test: []
overlap_size_test_perc: []
chunk_size_train: 200
overlap_size_train_perc: 0
dataset: mn_dataloader_def
perc_test_norm: 0.2
slices_for_train:
  folder: slices_for_training
  type_train: data_select
  perc_hyperpar: 0.4
filename: data/motoneurons/MNDS_TaSi2_10ClassesIMRLTTaToGrips_AllPost_IPD.mat
deltat: 1000
input_shape: []
kernel_size:
- 3
lc_ampl: 0.5
learning_rate: 1.e-6
loss: smoothL1
lr_drop_factor: 2
lr_drop_interval: 30
num_layers: 2
num_epochs: 100
num_conv_layers: 2
num_mlp_layers: 0
num_dl_workers: 4
optimizer: adamax
out_channels: 10
pool_size:
- 2
- 1
random_tau: False
reg_l:
- .0
- .0
- .0
- .0
test_interval: 1
init_theta:
- 5.e-5
- 5.e-5
- 5.e-5
- 5.e-5
muscle_to_exclude: []
class_to_include:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
thr_firing_excl_slice: 0
online_update: True
learning_method: 'rtrl'
